#!/usr/bin/env bash
################################################################################
#  Licensed to the Apache Software Foundation (ASF) under one
#  or more contributor license agreements.  See the NOTICE file
#  distributed with this work for additional information
#  regarding copyright ownership.  The ASF licenses this file
#  to you under the Apache License, Version 2.0 (the
#  "License"); you may not use this file except in compliance
#  with the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
# limitations under the License.
################################################################################

set -e
echo "David-cache-cron.sh script read cache!"
current_time_seconds=$(date +"%s")
current_time_milliseconds=$(( $(date '+%s%N') / 1000000));
echo "seconds $current_time_seconds"
echo "millis $current_time_milliseconds"
# Assisted by watsonx Code Assistant
# Code generated by WCA@IBM in this programming language is not approved for use in IBM product development.

# Define the directory containing the files
dir=$1
pwd
ls "$dir"
# Loop through the files in the directory
for file in "$dir"/*; do
  echo "file name is: $file"
  # Extract the time since epoch and the identifier using parameter expansion and regular expressions
  timestamp=${file#*-}  # Remove the filename prefix and capture the time since epoch
  prNumber=${file##*-}  # Remove the time since epoch and capture the identifier

  # Now you can use the $timestamp and $identifier variables as needed
  echo "Timestamp: $timestamp"
  echo "PR number: $prNumber"
done

