on:
  pull_request:
    types: [synchronize]
  pull_request_review:
    types: [submitted]

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: jsryudev/pr-review-labeler@v0.2.2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          target-approved-count: 1
          label-to-be-added: 'Accepted'
          label-to-be-removed: 'In Review'